#!/usr/bin/env python3
"""
ESP32 Web Assets Embedding Tool
CSS/JS/Faviconをgzip圧縮してESP32用ヘッダーファイルに変換
"""

import gzip
import os
import sys


def compress_file(file_path):
    """ファイルをgzip圧縮"""
    with open(file_path, 'r', encoding='utf-8') as f:
        content = f.read()
    return gzip.compress(content.encode('utf-8'), compresslevel=9)


def write_array(f, name, data, description):
    """C配列を出力"""
    f.write(f'\n// {description}\n')
    f.write(f'const uint32_t {name}_len = {len(data)};\n')
    f.write(f'const uint8_t {name}[] PROGMEM = {{\n  ')

    for i, byte in enumerate(data):
        f.write(f'0x{byte:02x}')
        if i < len(data) - 1:
            f.write(',')
            if (i + 1) % 16 == 0:
                f.write('\n  ')
            else:
                f.write(' ')

    f.write('\n};\n')


def main():
    # パス設定
    base_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    html_path = os.path.join(base_dir, 'gui/dist/index.html')
    css_path = os.path.join(base_dir, 'gui/dist/app.css')
    js_path = os.path.join(base_dir, 'gui/dist/app.js')
    favicon_path = os.path.join(base_dir, 'gui/public/favicon.svg')
    output_path = os.path.join(base_dir, 'esp32_app/WebAssets.h')

    # ファイル存在チェック
    files_to_check = [
        (html_path, 'HTML'),
        (css_path, 'CSS'),
        (js_path, 'JavaScript'),
        (favicon_path, 'Favicon')
    ]

    missing_files = []
    for path, name in files_to_check:
        if not os.path.exists(path):
            missing_files.append(f"{name}: {path}")

    if missing_files:
        print("❌ Error: Missing files:")
        for msg in missing_files:
            print(f"   - {msg}")
        sys.exit(1)

    print("📦 Compressing assets...")

    # ファイル圧縮
    html_gz = compress_file(html_path)
    css_gz = compress_file(css_path)
    js_gz = compress_file(js_path)
    favicon_gz = compress_file(favicon_path)

    # ヘッダーファイル生成
    print("📝 Generating WebAssets.h...")

    with open(output_path, 'w') as f:
        # ヘッダー
        f.write('// Auto-generated file - DO NOT EDIT MANUALLY\n')
        f.write('// Generated by tools/embed_assets.py\n')
        f.write('#ifndef WEB_ASSETS_H\n')
        f.write('#define WEB_ASSETS_H\n\n')
        f.write('#include <Arduino.h>\n')

        # HTML
        write_array(f, 'index_html_gz', html_gz, 'HTML (gzip compressed)')

        # CSS
        write_array(f, 'app_css_gz', css_gz, 'CSS (gzip compressed)')

        # JavaScript
        write_array(f, 'app_js_gz', js_gz, 'JavaScript (gzip compressed)')

        # Favicon
        write_array(f, 'favicon_svg_gz', favicon_gz,
                    'Favicon SVG (gzip compressed)')

        # フッター
        f.write('\n#endif // WEB_ASSETS_H\n')

    # サマリー表示
    total_size = len(html_gz) + len(css_gz) + len(js_gz) + len(favicon_gz)

    print("\n✅ WebAssets.h generated successfully!")
    print(f"\n📊 Asset sizes (gzip compressed):")
    print(f"   HTML:    {len(html_gz):>7,} bytes")
    print(f"   CSS:     {len(css_gz):>7,} bytes")
    print(f"   JS:      {len(js_gz):>7,} bytes")
    print(f"   Favicon: {len(favicon_gz):>7,} bytes")
    print(f"   {'─' * 24}")
    print(f"   Total:   {total_size:>7,} bytes ({total_size / 1024:.1f} KB)")


if __name__ == '__main__':
    main()
